require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.2.2
  NewCops: enable
  Exclude:
    - config/routes.rb
    - config/application.rb
    - config/environments/*
    - db/schema.rb
    - db/**/*
    - Gemfile
    - Gemfile.package
    - Guardfile
    - Rakefile
    - config.ru
    - vendors/**/*
    - bin/*

Style/Documentation:
  Enabled: false

Style/NumberedParameters:
  Enabled: false

Lint/EmptyClass:
  Enabled: false

Rails/DynamicFindBy:
  Enabled: false

Rails/InverseOf:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Metrics/MethodLength:
  Max: 20
  Exclude:
    - app/repositories/tasks_repository.rb

Metrics/AbcSize:
  Exclude:
    - app/consumers/*
    - app/repositories/tasks_repository.rb
