name: auth
services:
  auth_db:
    image: postgres:latest
    container_name: auth_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ates_auth
      POSTGRES_USER: ates_auth
    volumes:
      - ./volumes/auth_db:/var/lib/postgresql/data
    networks:
      - internal
  tasks_db:
    image: postgres:latest
    container_name: tasks_db
    environment:
      POSTGRES_DB: ates_tasks
      POSTGRES_USER: ates_tasks
    ports:
      - 5433:5432
    volumes:
      - ./volumes/tasks_db:/var/lib/postgresql/data
    networks:
      - internal

  billing_db:
    image: postgres:latest
    container_name: billing_db
    environment:
      POSTGRES_DB: ates_billing
      POSTGRES_USER: ates_billing
    ports:
      - 5434:5432
    volumes:
      - ./volumes/billing_db:/var/lib/postgresql/data
    networks:
      - internal

  analytics_db:
    image: postgres:latest
    container_name: analytics_db
    environment:
      POSTGRES_DB: ates_analytics
      POSTGRES_USER: ates_analytics
    ports:
      - 5435:5432
    volumes:
      - ./volumes/analytics_db:/var/lib/postgresql/data
    networks:
      - internal
      
  clickhouse:
    image: clickhouse/clickhouse-server:23.3.8
    container_name: clickhouse_db
    environment:
      CLICKHOUSE_DB: ates_clh
      CLICKHOUSE_USER: ates_clh
      CLICKHOUSE_PASSWORD: ates_clh
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    ports:
      - 8123:8123
      - 9000:9000
      - 9009:9009
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ./volumes/analytics_clickhouse:/var/lib/clickhouse
    networks:
      - internal

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.6.0
    user: "0:0"
    ports:
      - 9092:9092
    environment:
      CLUSTER_ID: kafka-docker-cluster-1
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
      KAFKA_BROKER_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@127.0.0.1:9093
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
      KAFKA_AUTHORIZER_CLASS_NAME: org.apache.kafka.metadata.authorizer.StandardAuthorizer
    volumes:
      - ./volumes/karafka:/var/lib/kafka/data

networks:
  internal:
    name: ates
