source "https://rubygems.org"

ruby "3.2.2"

# Use specific branch of Rails
gem "rails", github: "rails/rails", branch: "7-1-stable"

gem "dotenv-rails", "~> 3.0"

# Use postgresql as the database for Active Record
gem "pg", "~> 1.1"

# Use the Puma web server [https://github.com/puma/puma]
gem "puma", ">= 5.0"

gem "dry-struct", "~> 1.6"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ windows jruby ]

gem "dry-container", "~> 0.11.0"

gem 'diy-carrierable', github: 'diy-rb/diy-carrierable'

gem "aux", "~> 0.1.1"

gem "enumerize", "~> 2.7"

group :development, :test do
  gem 'yard', '~> 0.9.27', require: false
  gem 'byebug', '~> 11.1.3'
  gem "rubocop", "~> 1.60"
  gem "rubocop-rails", "~> 2.23"
end

group :test do
  gem "rswag", "~> 2.13"

  gem "database_cleaner", "~> 2.0"

  gem "rspec-rails", "~> 6.1"
end

# auth
gem 'omniauth', "~> 1.9.2"

gem "omniauth-oauth2", "~> 1.7"

gem "karafka", ">= 2.3.0"

gem "karafka-web", "~> 0.8.2"

gem "config", "~> 5.1"
