name: auth
services:
  postgres:
    image: postgres:latest
    container_name: auth_db
    env_file: .env
    ports:
      - 5433:5432
    volumes:
      - ates_auth:/var/lib/postgresql/data
    networks:
      - internal

volumes:
  ates_auth:

networks:
  internal:
    name: task_ates
