source "https://rubygems.org"

ruby "3.2.2"

# Use specific branch of Rails
gem "rails", github: "rails/rails", branch: "7-1-stable"

# Use postgresql as the database for Active Record
gem "pg", "~> 1.1"

# Use the Puma web server [https://github.com/puma/puma]
gem "puma", ">= 5.0"

# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem "kredis"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ windows jruby ]

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin Ajax possible
# gem "rack-cors"

group :development, :test do
  gem 'yard', '~> 0.9.27', require: false

  # Debugger
  gem 'byebug', '~> 11.1.3'

  # Code analysis and formatting
  gem "rubocop", "~> 1.60"
  # Rails-specific analysis
  gem "rubocop-rails", "~> 2.23"
end

group :development do
  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"
end


# Doorkeeper is a gem (Rails engine) that makes it easy to introduce OAuth 2 provider functionality to your Ruby on Rails or Grape application.
# https://github.com/doorkeeper-gem/doorkeeper
gem 'doorkeeper', '~> 5.4.0'

# Devise is a flexible authentication solution for Rails based on Warden
# https://github.com/heartcombo/devise
gem "devise", "~> 4.9"

gem "dotenv-rails", "~> 3.0"

gem "omniauth", "~> 2.1"

gem "omniauth-oauth2", "~> 1.8"
