source "https://rubygems.org"

ruby "3.2.2"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 7.1.3", ">= 7.1.3.2"

# The original asset pipeline for Rails [https://github.com/rails/sprockets-rails]
gem "sprockets-rails"

# Use postgresql as the database for Active Record
gem "pg", "~> 1.1"


# Use the Puma web server [https://github.com/puma/puma]
gem 'puma', '>= 5.0'

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ windows jruby ]

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

group :development, :test do
  gem "rubocop", "~> 1.61"
  gem "rubocop-rails", "~> 2.24"
  gem "byebug", "~> 11.1"
end

gem "config", "~> 5.3"

gem "dry-container", "~> 0.11.0"

gem "diy-carrierable", "~> 1.0", :github => "diy-rb/diy-carrierable"

gem "aux", "~> 0.1.1"

gem "karafka", "~> 2.3"
gem "omniauth-oauth2", "~> 1.8"
gem "omniauth", "~> 2.1"
gem "schema_registry", "~> 1", :path => "../events_schema_registry/ruby/"

gem "sidekiq", "~> 7.2"

gem "sidekiq-scheduler", "~> 5.0"
