# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.2.2'

# Use specific branch of Rails
gem 'rails', github: 'rails/rails', branch: '7-1-stable'

# The original asset pipeline for Rails [https://github.com/rails/sprockets-rails]
gem 'sprockets-rails'

# Use postgresql as the database for Active Record
gem 'pg', '~> 1.1'

# Use the Puma web server [https://github.com/puma/puma]
gem 'puma', '>= 5.0'

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[windows jruby]

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', require: false

group :development, :test do
  gem 'byebug', '~> 11.1'

  gem "rubocop", "~> 1.61"
  gem "rubocop-rails", "~> 2.24"
end

gem "config", "~> 5.1"

gem "aux", "~> 0.1.1"

gem "dry-container", "~> 0.11.0"
